// Central site config — update NEXT_PUBLIC_SITE_URL in your env to your real domain.
export const siteConfig = {
  name: "Zaid Ansari",
  title: "Zaid Ansari — AI & Full Stack Developer",
  shortTitle: "Zaid Ansari",
  description:
    "Zaid Ansari is an AI & Full Stack Developer with 3+ years of experience building intelligent, scalable web & mobile apps — integrating LLMs (OpenAI, Claude, Gemini) with React, Next.js, Node.js, NestJS & React Native.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://zaid-portfolio.vercel.app",
  locale: "en_US",
  email: "iamzaidansari166@gmail.com",
  github: "https://github.com/zaid-ansari166",
  linkedin: "https://www.linkedin.com/in/zaid-ansari-b27677295/",
  jobTitle: "AI & Full Stack Developer",
  location: "Indore, India",
  keywords: [
    "Zaid Ansari",
    "AI Developer",
    "AI Engineer",
    "Full Stack Developer",
    "MERN Stack Developer",
    "MEAN Stack Developer",
    "React Developer",
    "Next.js Developer",
    "React Native Developer",
    "Node.js Developer",
    "NestJS Developer",
    "LLM Integration",
    "OpenAI",
    "Claude AI",
    "Gemini",
    "Chatbot Developer",
    "RAG",
    "Prompt Engineering",
    "WebRTC Developer",
    "Software Engineer India",
    "Mobile App Developer",
    "Portfolio",
  ],
};
